backend:
  name: github
  repo: creadoras-de-exito/team-portal
  branch: main
  auth_type: implicit
  app_id: Ov23liBSRSBnxk8YsuSN

media_folder: 'public/uploads'
public_folder: '/uploads'

site_url: 'https://creadoras-de-exito-portal.netlify.app'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/hero/index.md'
        label: 'Home Page - Hero Section'
        name: 'home'
        fields:
          - { label: 'Hero Title', name: 'title', widget: 'string' }
          - { label: 'Director', name: 'director', widget: 'string', required: false }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Background Image', name: 'backgroundImage', widget: 'image' }
          - label: 'Links'
            name: 'links'
            widget: 'list'
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'To', name: 'to', widget: 'string' }
              - { label: 'Trailing Icon', name: 'trailingIcon', widget: 'string', required: false }
              - { label: 'Size', name: 'size', widget: 'select', options: ['sm', 'md', 'lg', 'xl'], default: 'md' }
  - name: 'components'
    label: 'Components'
    files:
      - file: 'content/components/about-section.md'
        label: 'Home Page - About Section'
        name: 'aboutSection'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
